// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lLOCALS.Data;

#nullable disable

namespace lLOCAlS.Migrations
{
    [DbContext(typeof(LocalsContext))]
    [Migration("20260107110442_InitialLlocalsSetup")]
    partial class InitialLlocalsSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("lLOCALS.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "مطاعم وكافيهات"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "أماكن ترفيهية"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "حدائق ومنتزهات"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "مراكز تسوق"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "متاحف ومعالم تاريخية"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "أنشطة رياضية"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "فعاليات ومواسم"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "فنادق وإقامات"
                        });
                });

            modelBuilder.Entity("lLOCALS.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DistrictId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            Name = "حي الملقا"
                        },
                        new
                        {
                            DistrictId = 2,
                            Name = "حي حطين"
                        },
                        new
                        {
                            DistrictId = 3,
                            Name = "حي النخيل"
                        },
                        new
                        {
                            DistrictId = 4,
                            Name = "حي الدرعية"
                        },
                        new
                        {
                            DistrictId = 5,
                            Name = "حي العليا"
                        },
                        new
                        {
                            DistrictId = 6,
                            Name = "حي الياسمين"
                        },
                        new
                        {
                            DistrictId = 7,
                            Name = "حي النرجس"
                        },
                        new
                        {
                            DistrictId = 8,
                            Name = "حي السليمانية"
                        });
                });

            modelBuilder.Entity("lLOCALS.Models.Place", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceId"));

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlaceId");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Places");
                });

            modelBuilder.Entity("lLOCALS.Models.PlaceImage", b =>
                {
                    b.Property<int>("PlaceImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceImageId"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("PlaceImageId");

                    b.HasIndex("PlaceId");

                    b.ToTable("PlaceImages");
                });

            modelBuilder.Entity("lLOCALS.Models.UpgradeRequest", b =>
                {
                    b.Property<int>("UpgradeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpgradeRequestId"));

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UpgradeRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("UpgradeRequests");
                });

            modelBuilder.Entity("lLOCALS.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("lLOCALS.Models.Place", b =>
                {
                    b.HasOne("lLOCALS.Models.User", "AddedByUser")
                        .WithMany("Places")
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lLOCALS.Models.Category", "Category")
                        .WithMany("Places")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lLOCALS.Models.District", "District")
                        .WithMany("Places")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByUser");

                    b.Navigation("Category");

                    b.Navigation("District");
                });

            modelBuilder.Entity("lLOCALS.Models.PlaceImage", b =>
                {
                    b.HasOne("lLOCALS.Models.Place", "Place")
                        .WithMany("Images")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("lLOCALS.Models.UpgradeRequest", b =>
                {
                    b.HasOne("lLOCALS.Models.User", "User")
                        .WithMany("UpgradeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("lLOCALS.Models.Category", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("lLOCALS.Models.District", b =>
                {
                    b.Navigation("Places");
                });

            modelBuilder.Entity("lLOCALS.Models.Place", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("lLOCALS.Models.User", b =>
                {
                    b.Navigation("Places");

                    b.Navigation("UpgradeRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
